version: '3.8'

services:
  skycrops-frontend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    networks:
      - skycrops-network

networks:
  skycrops-network:
    driver: bridge
